version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  docker: circleci/docker@2.1.1
  helm: circleci/helm@2.0.1
  kubernetes: circleci/kubernetes@1.3.0
  
jobs:
  deploy-system:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      # Installing pre-req software if not already present
      - docker/install-docker
      - aws-cli/install
      - kubernetes/install-kubectl
      - helm/install-helm-client

      # AWS Setup, sensative data stored in private environment variables
      - aws-cli/setup:
          aws-access-key-id: AWS_AccessKeyId 
          aws-region: AWS_Region 
          aws-secret-access-key: AWS_SecretAccessKey
          profile-name: at-interviews 

      # Initialize docker instance
      - setup_remote_docker

      # Listing what files/folders exist after setup
      - run:
          name: "List local files"
          command: "ls -a"

      # Run the local-deploy script
      - run:
          name: "Run local-deploy.sh"
          command: "bash local-deploy.sh"

workflows:
  deployment-workflow:
    jobs:
      - deploy-system
